[package]
authors = ["Jake O'Shannessy <joshannessy@affinity-eng.com>"]
edition = "2018"
name = "ms-oxmsg"
version = "0.1.0"

[dependencies]
bitflags = "1.3.2"
cfb = "0.6"
chrono = {version = "0.4", features = ["serde"]}
crc = "2"
serde = {version = "1", features = ["derive"]}
uuid = "0.8"
