[package]
name = "ms-oxmsg"
version = "0.1.0"
authors = ["Jake O'Shannessy <joshannessy@affinity-eng.com>"]
edition = "2018"

[dependencies]
cfb = "0.6"
uuid = "0.8"
serde = { version = "1", features = ["derive"] }
crc = "2"
chrono = "0.4"

[dev-dependencies]
