#[derive(Copy, Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum Tag {
    Access,
    AccessControlListData,
    AccessLevel,
    Account,
    AdditionalRenEntryIds,
    AdditionalRenEntryIdsEx,
    AddressBookAuthorizedSenders,
    AddressBookContainerId,
    AddressBookDeliveryContentLength,
    AddressBookDisplayNamePrintable,
    AddressBookDisplayTypeExtended,
    AddressBookDistributionListExternalMemberCount,
    AddressBookDistributionListMemberCount,
    AddressBookDistributionListMemberSubmitAccepted,
    AddressBookDistributionListMemberSubmitRejected,
    AddressBookDistributionListRejectMessagesFromDLMembers,
    AddressBookEntryId,
    AddressBookExtensionAttribute1,
    AddressBookExtensionAttribute10,
    AddressBookExtensionAttribute11,
    AddressBookExtensionAttribute12,
    AddressBookExtensionAttribute13,
    AddressBookExtensionAttribute14,
    AddressBookExtensionAttribute15,
    AddressBookExtensionAttribute2,
    AddressBookExtensionAttribute3,
    AddressBookExtensionAttribute4,
    AddressBookExtensionAttribute5,
    AddressBookExtensionAttribute6,
    AddressBookExtensionAttribute7,
    AddressBookExtensionAttribute8,
    AddressBookExtensionAttribute9,
    AddressBookFolderPathname,
    AddressBookHierarchicalChildDepartments,
    AddressBookHierarchicalDepartmentMembers,
    AddressBookHierarchicalIsHierarchicalGroup,
    AddressBookHierarchicalParentDepartment,
    AddressBookHierarchicalRootDepartment,
    AddressBookHierarchicalShowInDepartments,
    AddressBookIsMaster,
    AddressBookManageDistributionList,
    AddressBookManager,
    AddressBookManagerDistinguishedName,
    AddressBookMember,
    AddressBookMessageId,
    AddressBookModerationEnabled,
    AddressBookNetworkAddress,
    AddressBookObjectDistinguishedName,
    AddressBookObjectGuid,
    AddressBookOrganizationalUnitRootDistinguishedName,
    AddressBookOwner,
    AddressBookOwnerBackLink,
    AddressBookParentEntryId,
    AddressBookPhoneticCompanyName,
    AddressBookPhoneticDepartmentName,
    AddressBookPhoneticDisplayName,
    AddressBookPhoneticGivenName,
    AddressBookPhoneticSurname,
    AddressBookProxyAddresses,
    AddressBookPublicDelegates,
    AddressBookReports,
    AddressBookRoomCapacity,
    AddressBookRoomContainers,
    AddressBookRoomDescription,
    AddressBookSenderHintTranslations,
    AddressBookSeniorityIndex,
    AddressBookTargetAddress,
    AddressBookUnauthorizedSenders,
    AddressBookX509Certificate,
    AddressType,
    AlternateRecipientAllowed,
    Anr,
    ArchiveDate,
    ArchivePeriod,
    ArchiveTag,
    Assistant,
    AssistantTelephoneNumber,
    Associated,
    AttachAdditionalInformation,
    AttachContentBase,
    AttachContentId,
    AttachContentLocation,
    AttachDataBinary,
    AttachDataObject,
    AttachEncoding,
    AttachExtension,
    AttachFilename,
    AttachFlags,
    AttachLongFilename,
    AttachLongPathname,
    AttachmentContactPhoto,
    AttachmentFlags,
    AttachmentHidden,
    AttachmentLinkId,
    AttachMethod,
    AttachMimeTag,
    AttachNumber,
    AttachPathname,
    AttachPayloadClass,
    AttachPayloadProviderGuidString,
    AttachRendering,
    AttachSize,
    AttachTag,
    AttachTransportName,
    AttributeHidden,
    AttributeReadOnly,
    AutoForwardComment,
    AutoForwarded,
    AutoResponseSuppress,
    Birthday,
    BlockStatus,
    Body,
    BodyContentId,
    BodyContentLocation,
    BodyHtml,
    Business2TelephoneNumber,
    Business2TelephoneNumbers,
    BusinessFaxNumber,
    BusinessHomePage,
    BusinessTelephoneNumber,
    CallbackTelephoneNumber,
    CallId,
    CarTelephoneNumber,
    CdoRecurrenceid,
    ChangeKey,
    ChangeNumber,
    ChildrensNames,
    ClientActions,
    ClientSubmitTime,
    CodePageId,
    Comment,
    CompanyMainTelephoneNumber,
    CompanyName,
    ComputerNetworkName,
    ConflictEntryId,
    ContainerClass,
    ContainerContents,
    ContainerFlags,
    ContainerHierarchy,
    ContentCount,
    ContentFilterSpamConfidenceLevel,
    ContentUnreadCount,
    ConversationId,
    ConversationIndex,
    ConversationIndexTracking,
    ConversationTopic,
    Country,
    CreationTime,
    CreatorEntryId,
    CreatorName,
    CustomerId,
    DamBackPatched,
    DamOriginalEntryId,
    DefaultPostMessageClass,
    DeferredActionMessageOriginalEntryId,
    DeferredDeliveryTime,
    DeferredSendNumber,
    DeferredSendTime,
    DeferredSendUnits,
    DelegatedByRule,
    DelegateFlags,
    DeleteAfterSubmit,
    DeletedCountTotal,
    DeletedOn,
    DeliverTime,
    DepartmentName,
    Depth,
    DisplayBcc,
    DisplayCc,
    DisplayName,
    DisplayNamePrefix,
    DisplayTo,
    DisplayType,
    DisplayTypeEx,
    EmailAddress,
    EndDate,
    EntryId,
    ExceptionEndTime,
    ExceptionReplaceTime,
    ExceptionStartTime,
    ExchangeNTSecurityDescriptor,
    ExpiryNumber,
    ExpiryTime,
    ExpiryUnits,
    ExtendedFolderFlags,
    ExtendedRuleMessageActions,
    ExtendedRuleMessageCondition,
    ExtendedRuleSizeLimit,
    FaxNumberOfPages,
    FlagCompleteTime,
    FlagStatus,
    FlatUrlName,
    FolderAssociatedContents,
    FolderId,
    FolderFlags,
    FolderType,
    FollowupIcon,
    FreeBusyCountMonths,
    FreeBusyEntryIds,
    FreeBusyMessageEmailAddress,
    FreeBusyPublishEnd,
    FreeBusyPublishStart,
    FreeBusyRangeTimestamp,
    FtpSite,
    GatewayNeedsToRefresh,
    Gender,
    Generation,
    GivenName,
    GovernmentIdNumber,
    HasAttachments,
    HasDeferredActionMessages,
    HasNamedProperties,
    HasRules,
    HierarchyChangeNumber,
    HierRev,
    Hobbies,
    Home2TelephoneNumber,
    Home2TelephoneNumbers,
    HomeAddressCity,
    HomeAddressCountry,
    HomeAddressPostalCode,
    HomeAddressPostOfficeBox,
    HomeAddressStateOrProvince,
    HomeAddressStreet,
    HomeFaxNumber,
    HomeTelephoneNumber,
    Html,
    ICalendarEndTime,
    ICalendarReminderNextTime,
    ICalendarStartTime,
    IconIndex,
    Importance,
    InConflict,
    InitialDetailsPane,
    Initials,
    InReplyToId,
    InstanceKey,
    InstanceNum,
    InstID,
    InternetCodepage,
    InternetMailOverrideFormat,
    InternetMessageId,
    InternetReferences,
    IpmAppointmentEntryId,
    IpmContactEntryId,
    IpmDraftsEntryId,
    IpmJournalEntryId,
    IpmNoteEntryId,
    IpmTaskEntryId,
    IsdnNumber,
    JunkAddRecipientsToSafeSendersList,
    JunkIncludeContacts,
    JunkPermanentlyDelete,
    JunkPhishingEnableLinks,
    JunkThreshold,
    Keyword,
    Language,
    LastModificationTime,
    LastModifierEntryId,
    LastModifierName,
    LastVerbExecuted,
    LastVerbExecutionTime,
    ListHelp,
    ListSubscribe,
    ListUnsubscribe,
    LocalCommitTime,
    LocalCommitTimeMax,
    LocaleId,
    Locality,
    Location,
    MailboxOwnerEntryId,
    MailboxOwnerName,
    ManagerName,
    MappingSignature,
    MaximumSubmitMessageSize,
    MemberId,
    MemberName,
    MemberRights,
    MessageAttachments,
    MessageCcMe,
    MessageClass,
    MessageCodepage,
    MessageDeliveryTime,
    MessageEditorFormat,
    MessageFlags,
    MessageHandlingSystemCommonName,
    MessageLocaleId,
    MessageRecipientMe,
    MessageRecipients,
    MessageSize,
    MessageSizeExtended,
    MessageStatus,
    MessageSubmissionId,
    MessageToMe,
    Mid,
    MiddleName,
    MimeSkeleton,
    MobileTelephoneNumber,
    NativeBody,
    NextSendAcct,
    Nickname,
    NonDeliveryReportDiagCode,
    NonDeliveryReportReasonCode,
    NonDeliveryReportStatusCode,
    // export const nReceiptNotificationRequested,
    NormalizedSubject,
    ObjectType,
    OfficeLocation,
    OfflineAddressBookContainerGuid,
    OfflineAddressBookDistinguishedName,
    OfflineAddressBookMessageClass,
    OfflineAddressBookName,
    OfflineAddressBookSequence,
    OfflineAddressBookTruncatedProperties,
    OrdinalMost,
    OrganizationalIdNumber,
    OriginalAuthorEntryId,
    OriginalAuthorName,
    OriginalDeliveryTime,
    OriginalDisplayBcc,
    OriginalDisplayCc,
    OriginalDisplayTo,
    OriginalEntryId,
    OriginalMessageClass,
    OriginalMessageId,
    OriginalSenderAddressType,
    OriginalSenderEmailAddress,
    OriginalSenderEntryId,
    OriginalSenderName,
    OriginalSenderSearchKey,
    OriginalSensitivity,
    OriginalSentRepresentingAddressType,
    OriginalSentRepresentingEmailAddress,
    OriginalSentRepresentingEntryId,
    OriginalSentRepresentingName,
    OriginalSentRepresentingSearchKey,
    OriginalSubject,
    OriginalSubmitTime,
    OriginatorDeliveryReportRequested,
    OriginatorNonDeliveryReportRequested,
    OscSyncEnabled,
    OtherAddressCity,
    OtherAddressCountry,
    OtherAddressPostalCode,
    OtherAddressPostOfficeBox,
    OtherAddressStateOrProvince,
    OtherAddressStreet,
    OtherTelephoneNumber,
    OutOfOfficeState,
    OwnerAppointmentId,
    PagerTelephoneNumber,
    ParentEntryId,
    ParentFolderId,
    ParentKey,
    ParentSourceKey,
    PersonalHomePage,
    PolicyTag,
    PostalAddress,
    PostalCode,
    PostOfficeBox,
    PredecessorChangeList,
    ProviderSubmitTime,
    PrimaryFaxNumber,
    PrimarySendAccount,
    PrimaryTelephoneNumber,
    Priority,
    Processed,
    Profession,
    ProhibitReceiveQuota,
    ProhibitSendQuota,
    PurportedSenderDomain,
    RadioTelephoneNumber,
    Read,
    ReadReceiptAddressType,
    ReadReceiptEmailAddress,
    ReadReceiptEntryId,
    ReadReceiptName,
    ReadReceiptRequested,
    ReadReceiptSearchKey,
    ReadReceiptSmtpAddress,
    ReceiptTime,
    ReceivedByAddressType,
    ReceivedByEmailAddress,
    ReceivedByEntryId,
    ReceivedByName,
    ReceivedBySearchKey,
    ReceivedBySmtpAddress,
    ReceivedRepresentingAddressType,
    ReceivedRepresentingEmailAddress,
    ReceivedRepresentingEntryId,
    ReceivedRepresentingName,
    ReceivedRepresentingSearchKey,
    ReceivedRepresentingSmtpAddress,
    RecipientDisplayName,
    RecipientEntryId,
    RecipientFlags,
    RecipientOrder,
    RecipientProposed,
    RecipientProposedEndTime,
    RecipientProposedStartTime,
    RecipientReassignmentProhibited,
    RecipientTrackStatus,
    RecipientTrackStatusTime,
    RecipientType,
    RecordKey,
    ReferredByName,
    RemindersOnlineEntryId,
    RemoteMessageTransferAgent,
    RenderingPosition,
    ReplyRecipientEntries,
    ReplyRecipientNames,
    ReplyRequested,
    ReplyTemplateId,
    ReplyTime,
    ReportDisposition,
    ReportDispositionMode,
    ReportEntryId,
    ReportingMessageTransferAgent,
    ReportName,
    ReportSearchKey,
    ReportTag,
    ReportText,
    ReportTime,
    ResolveMethod,
    ResponseRequested,
    Responsibility,
    RetentionDate,
    RetentionFlags,
    RetentionPeriod,
    Rights,
    RoamingDatatypes,
    RoamingDictionary,
    RoamingXmlStream,
    Rowid,
    RowType,
    RtfCompressed,
    RtfInSync,
    RuleActionNumber,
    RuleActions,
    RuleActionType,
    RuleCondition,
    RuleError,
    RuleFolderEntryId,
    RuleId,
    RuleIds,
    RuleLevel,
    RuleMessageLevel,
    RuleMessageName,
    RuleMessageProvider,
    RuleMessageProviderData,
    RuleMessageSequence,
    RuleMessageState,
    RuleMessageUserFlags,
    RuleName,
    RuleProvider,
    RuleProviderData,
    RuleSequence,
    RuleState,
    RuleUserFlags,
    RwRulesStream,
    ScheduleInfoAppointmentTombstone,
    ScheduleInfoAutoAcceptAppointments,
    ScheduleInfoDelegateEntryIds,
    ScheduleInfoDelegateNames,
    ScheduleInfoDelegateNamesW,
    ScheduleInfoDelegatorWantsCopy,
    ScheduleInfoDelegatorWantsInfo,
    ScheduleInfoDisallowOverlappingAppts,
    ScheduleInfoDisallowRecurringAppts,
    ScheduleInfoDontMailDelegates,
    ScheduleInfoFreeBusy,
    ScheduleInfoFreeBusyAway,
    ScheduleInfoFreeBusyBusy,
    ScheduleInfoFreeBusyMerged,
    ScheduleInfoFreeBusyTentative,
    ScheduleInfoMonthsAway,
    ScheduleInfoMonthsBusy,
    ScheduleInfoMonthsMerged,
    ScheduleInfoMonthsTentative,
    ScheduleInfoResourceType,
    SchedulePlusFreeBusyEntryId,
    ScriptData,
    SearchFolderDefinition,
    SearchFolderEfpFlags,
    SearchFolderExpiration,
    SearchFolderId,
    SearchFolderLastUsed,
    SearchFolderRecreateInfo,
    SearchFolderStorageType,
    SearchFolderTag,
    SearchFolderTemplateId,
    SearchKey,
    SecurityDescriptorAsXml,
    Selectable,
    SenderAddressType,
    SenderEmailAddress,
    SenderEntryId,
    SenderIdStatus,
    SenderName,
    SenderSearchKey,
    SenderSmtpAddress,
    SenderTelephoneNumber,
    SendInternetEncoding,
    SendRichInfo,
    Sensitivity,
    SentMailSvrEID,
    SentMailEntryId,
    SentRepresentingAddressType,
    SentRepresentingEmailAddress,
    SentRepresentingEntryId,
    SentRepresentingFlags,
    SentRepresentingName,
    SentRepresentingSearchKey,
    SentRepresentingSmtpAddress,
    SerializedReplidGuidMap,
    SmtpAddress,
    SortLocaleId,
    SourceKey,
    SpokenName,
    SpouseName,
    StartDate,
    StartDateEtc,
    StateOrProvince,
    StoreEntryId,
    StoreState,
    StoreSupportMask,
    StreetAddress,
    Subfolders,
    Subject,
    SubjectPrefix,
    SupplementaryInfo,
    Surname,
    SwappedToDoData,
    SwappedToDoStore,
    TargetEntryId,
    TelecommunicationsDeviceForDeafTelephoneNumber,
    TemplateData,
    Templateid,
    TextAttachmentCharset,
    ThumbnailPhoto,
    Title,
    TnefCorrelationKey,
    ToDoItemFlags,
    TransmittableDisplayName,
    TransportMessageHeaders,
    TrustSender,
    UserCertificate,
    UserEntryId,
    UserX509Certificate,
    ViewDescriptorBinary,
    ViewDescriptorName,
    ViewDescriptorStrings,
    ViewDescriptorVersion,
    VoiceMessageAttachmentOrder,
    VoiceMessageDuration,
    VoiceMessageSenderName,
    WeddingAnniversary,
    WlinkAddressBookEID,
    WlinkAddressBookStoreEID,
    WlinkCalendarColor,
    WlinkClientID,
    WlinkEntryId,
    WlinkFlags,
    WlinkFolderType,
    WlinkGroupClsid,
    WlinkGroupHeaderID,
    WlinkGroupName,
    WlinkOrdinal,
    WlinkRecordKey,
    WlinkROGroupType,
    WlinkSaveStamp,
    WlinkSection,
    WlinkStoreEntryId,
    WlinkType,
    Mapped(u16),
    Unknown(u16),
}

impl Tag {
    pub fn from_u16(n: u16) -> Self {
        match n {
            0x0FF4 => Self::Access,
            0x3FE0 => Self::AccessControlListData,
            0x0FF7 => Self::AccessLevel,
            0x3A00 => Self::Account,
            0x36D8 => Self::AdditionalRenEntryIds,
            0x36D9 => Self::AdditionalRenEntryIdsEx,
            0x8CD8 => Self::AddressBookAuthorizedSenders,
            0xFFFD => Self::AddressBookContainerId,
            0x806A => Self::AddressBookDeliveryContentLength,
            0x39FF => Self::AddressBookDisplayNamePrintable,
            0x8C93 => Self::AddressBookDisplayTypeExtended,
            0x8CE3 => Self::AddressBookDistributionListExternalMemberCount,
            0x8CE2 => Self::AddressBookDistributionListMemberCount,
            0x8073 => Self::AddressBookDistributionListMemberSubmitAccepted,
            0x8CDA => Self::AddressBookDistributionListMemberSubmitRejected,
            0x8CDB => Self::AddressBookDistributionListRejectMessagesFromDLMembers,
            0x663B => Self::AddressBookEntryId,
            0x802D => Self::AddressBookExtensionAttribute1,
            0x8036 => Self::AddressBookExtensionAttribute10,
            0x8C57 => Self::AddressBookExtensionAttribute11,
            0x8C58 => Self::AddressBookExtensionAttribute12,
            0x8C59 => Self::AddressBookExtensionAttribute13,
            0x8C60 => Self::AddressBookExtensionAttribute14,
            0x8C61 => Self::AddressBookExtensionAttribute15,
            0x802E => Self::AddressBookExtensionAttribute2,
            0x802F => Self::AddressBookExtensionAttribute3,
            0x8030 => Self::AddressBookExtensionAttribute4,
            0x8031 => Self::AddressBookExtensionAttribute5,
            0x8032 => Self::AddressBookExtensionAttribute6,
            0x8033 => Self::AddressBookExtensionAttribute7,
            0x8034 => Self::AddressBookExtensionAttribute8,
            0x8035 => Self::AddressBookExtensionAttribute9,
            0x8004 => Self::AddressBookFolderPathname,
            0x8C9A => Self::AddressBookHierarchicalChildDepartments,
            0x8C97 => Self::AddressBookHierarchicalDepartmentMembers,
            0x8CDD => Self::AddressBookHierarchicalIsHierarchicalGroup,
            0x8C99 => Self::AddressBookHierarchicalParentDepartment,
            0x8C98 => Self::AddressBookHierarchicalRootDepartment,
            0x8C94 => Self::AddressBookHierarchicalShowInDepartments,
            0xFFFB => Self::AddressBookIsMaster,
            0x6704 => Self::AddressBookManageDistributionList,
            0x8005 => Self::AddressBookManager,
            0x8005 => Self::AddressBookManagerDistinguishedName,
            0x8009 => Self::AddressBookMember,
            0x674F => Self::AddressBookMessageId,
            0x8CB5 => Self::AddressBookModerationEnabled,
            0x8170 => Self::AddressBookNetworkAddress,
            0x803C => Self::AddressBookObjectDistinguishedName,
            0x8C6D => Self::AddressBookObjectGuid,
            0x8CA8 => Self::AddressBookOrganizationalUnitRootDistinguishedName,
            0x800C => Self::AddressBookOwner,
            0x8024 => Self::AddressBookOwnerBackLink,
            0xFFFC => Self::AddressBookParentEntryId,
            0x8C91 => Self::AddressBookPhoneticCompanyName,
            0x8C90 => Self::AddressBookPhoneticDepartmentName,
            0x8C92 => Self::AddressBookPhoneticDisplayName,
            0x8C8E => Self::AddressBookPhoneticGivenName,
            0x8C8F => Self::AddressBookPhoneticSurname,
            0x800F => Self::AddressBookProxyAddresses,
            0x8015 => Self::AddressBookPublicDelegates,
            0x800E => Self::AddressBookReports,
            0x0807 => Self::AddressBookRoomCapacity,
            0x8C96 => Self::AddressBookRoomContainers,
            0x0809 => Self::AddressBookRoomDescription,
            0x8CAC => Self::AddressBookSenderHintTranslations,
            0x8CA0 => Self::AddressBookSeniorityIndex,
            0x8011 => Self::AddressBookTargetAddress,
            0x8CD9 => Self::AddressBookUnauthorizedSenders,
            0x8C6A => Self::AddressBookX509Certificate,
            0x3002 => Self::AddressType,
            0x0002 => Self::AlternateRecipientAllowed,
            0x360C => Self::Anr,
            0x301F => Self::ArchiveDate,
            0x301E => Self::ArchivePeriod,
            0x3018 => Self::ArchiveTag,
            0x3A30 => Self::Assistant,
            0x3A2E => Self::AssistantTelephoneNumber,
            0x67AA => Self::Associated,
            0x370F => Self::AttachAdditionalInformation,
            0x3711 => Self::AttachContentBase,
            0x3712 => Self::AttachContentId,
            0x3713 => Self::AttachContentLocation,
            0x3701 => Self::AttachDataBinary,
            0x3701 => Self::AttachDataObject,
            0x3702 => Self::AttachEncoding,
            0x3703 => Self::AttachExtension,
            0x3704 => Self::AttachFilename,
            0x3714 => Self::AttachFlags,
            0x3707 => Self::AttachLongFilename,
            0x370D => Self::AttachLongPathname,
            0x7FFF => Self::AttachmentContactPhoto,
            0x7FFD => Self::AttachmentFlags,
            0x7FFE => Self::AttachmentHidden,
            0x7FFA => Self::AttachmentLinkId,
            0x3705 => Self::AttachMethod,
            0x370E => Self::AttachMimeTag,
            0x0E21 => Self::AttachNumber,
            0x3708 => Self::AttachPathname,
            0x371A => Self::AttachPayloadClass,
            0x3719 => Self::AttachPayloadProviderGuidString,
            0x3709 => Self::AttachRendering,
            0x0E20 => Self::AttachSize,
            0x370A => Self::AttachTag,
            0x370C => Self::AttachTransportName,
            0x10F4 => Self::AttributeHidden,
            0x10F6 => Self::AttributeReadOnly,
            0x0004 => Self::AutoForwardComment,
            0x0005 => Self::AutoForwarded,
            0x3FDF => Self::AutoResponseSuppress,
            0x3A42 => Self::Birthday,
            0x1096 => Self::BlockStatus,
            0x1000 => Self::Body,
            0x1015 => Self::BodyContentId,
            0x1014 => Self::BodyContentLocation,
            0x1013 => Self::BodyHtml,
            0x3A1B => Self::Business2TelephoneNumber,
            0x3A1B => Self::Business2TelephoneNumbers,
            0x3A24 => Self::BusinessFaxNumber,
            0x3A51 => Self::BusinessHomePage,
            0x3A08 => Self::BusinessTelephoneNumber,
            0x3A02 => Self::CallbackTelephoneNumber,
            0x6806 => Self::CallId,
            0x3A1E => Self::CarTelephoneNumber,
            0x10C5 => Self::CdoRecurrenceid,
            0x65E2 => Self::ChangeKey,
            0x67A4 => Self::ChangeNumber,
            0x3A58 => Self::ChildrensNames,
            0x6645 => Self::ClientActions,
            0x0039 => Self::ClientSubmitTime,
            0x66C3 => Self::CodePageId,
            0x3004 => Self::Comment,
            0x3A57 => Self::CompanyMainTelephoneNumber,
            0x3A16 => Self::CompanyName,
            0x3A49 => Self::ComputerNetworkName,
            0x3FF0 => Self::ConflictEntryId,
            0x3613 => Self::ContainerClass,
            0x360F => Self::ContainerContents,
            0x3600 => Self::ContainerFlags,
            0x360E => Self::ContainerHierarchy,
            0x3602 => Self::ContentCount,
            0x4076 => Self::ContentFilterSpamConfidenceLevel,
            0x3603 => Self::ContentUnreadCount,
            0x3013 => Self::ConversationId,
            0x0071 => Self::ConversationIndex,
            0x3016 => Self::ConversationIndexTracking,
            0x0070 => Self::ConversationTopic,
            0x3A26 => Self::Country,
            0x3007 => Self::CreationTime,
            0x3FF9 => Self::CreatorEntryId,
            0x3FF8 => Self::CreatorName,
            0x3A4A => Self::CustomerId,
            0x6647 => Self::DamBackPatched,
            0x6646 => Self::DamOriginalEntryId,
            0x36E5 => Self::DefaultPostMessageClass,
            0x6741 => Self::DeferredActionMessageOriginalEntryId,
            0x000F => Self::DeferredDeliveryTime,
            0x3FEB => Self::DeferredSendNumber,
            0x3FEF => Self::DeferredSendTime,
            0x3FEC => Self::DeferredSendUnits,
            0x3FE3 => Self::DelegatedByRule,
            0x686B => Self::DelegateFlags,
            0x0E01 => Self::DeleteAfterSubmit,
            0x670B => Self::DeletedCountTotal,
            0x668F => Self::DeletedOn,
            0x0010 => Self::DeliverTime,
            0x3A18 => Self::DepartmentName,
            0x3005 => Self::Depth,
            0x0E02 => Self::DisplayBcc,
            0x0E03 => Self::DisplayCc,
            0x3001 => Self::DisplayName,
            0x3A45 => Self::DisplayNamePrefix,
            0x0E04 => Self::DisplayTo,
            0x3900 => Self::DisplayType,
            0x3905 => Self::DisplayTypeEx,
            0x3003 => Self::EmailAddress,
            0x0061 => Self::EndDate,
            0x0FFF => Self::EntryId,
            0x7FFC => Self::ExceptionEndTime,
            0x7FF9 => Self::ExceptionReplaceTime,
            0x7FFB => Self::ExceptionStartTime,
            0x0E84 => Self::ExchangeNTSecurityDescriptor,
            0x3FED => Self::ExpiryNumber,
            0x0015 => Self::ExpiryTime,
            0x3FEE => Self::ExpiryUnits,
            0x36DA => Self::ExtendedFolderFlags,
            0x0E99 => Self::ExtendedRuleMessageActions,
            0x0E9A => Self::ExtendedRuleMessageCondition,
            0x0E9B => Self::ExtendedRuleSizeLimit,
            0x6804 => Self::FaxNumberOfPages,
            0x1091 => Self::FlagCompleteTime,
            0x1090 => Self::FlagStatus,
            0x670E => Self::FlatUrlName,
            0x3610 => Self::FolderAssociatedContents,
            0x6748 => Self::FolderId,
            0x66A8 => Self::FolderFlags,
            0x3601 => Self::FolderType,
            0x1095 => Self::FollowupIcon,
            0x6869 => Self::FreeBusyCountMonths,
            0x36E4 => Self::FreeBusyEntryIds,
            0x6849 => Self::FreeBusyMessageEmailAddress,
            0x6848 => Self::FreeBusyPublishEnd,
            0x6847 => Self::FreeBusyPublishStart,
            0x6868 => Self::FreeBusyRangeTimestamp,
            0x3A4C => Self::FtpSite,
            0x6846 => Self::GatewayNeedsToRefresh,
            0x3A4D => Self::Gender,
            0x3A05 => Self::Generation,
            0x3A06 => Self::GivenName,
            0x3A07 => Self::GovernmentIdNumber,
            0x0E1B => Self::HasAttachments,
            0x3FEA => Self::HasDeferredActionMessages,
            0x664A => Self::HasNamedProperties,
            0x663A => Self::HasRules,
            0x663E => Self::HierarchyChangeNumber,
            0x4082 => Self::HierRev,
            0x3A43 => Self::Hobbies,
            0x3A2F => Self::Home2TelephoneNumber,
            0x3A2F => Self::Home2TelephoneNumbers,
            0x3A59 => Self::HomeAddressCity,
            0x3A5A => Self::HomeAddressCountry,
            0x3A5B => Self::HomeAddressPostalCode,
            0x3A5E => Self::HomeAddressPostOfficeBox,
            0x3A5C => Self::HomeAddressStateOrProvince,
            0x3A5D => Self::HomeAddressStreet,
            0x3A25 => Self::HomeFaxNumber,
            0x3A09 => Self::HomeTelephoneNumber,
            0x1013 => Self::Html,
            0x10C4 => Self::ICalendarEndTime,
            0x10CA => Self::ICalendarReminderNextTime,
            0x10C3 => Self::ICalendarStartTime,
            0x1080 => Self::IconIndex,
            0x0017 => Self::Importance,
            0x666C => Self::InConflict,
            0x3F08 => Self::InitialDetailsPane,
            0x3A0A => Self::Initials,
            0x1042 => Self::InReplyToId,
            0x0FF6 => Self::InstanceKey,
            0x674E => Self::InstanceNum,
            0x674D => Self::InstID,
            0x3FDE => Self::InternetCodepage,
            0x5902 => Self::InternetMailOverrideFormat,
            0x1035 => Self::InternetMessageId,
            0x1039 => Self::InternetReferences,
            0x36D0 => Self::IpmAppointmentEntryId,
            0x36D1 => Self::IpmContactEntryId,
            0x36D7 => Self::IpmDraftsEntryId,
            0x36D2 => Self::IpmJournalEntryId,
            0x36D3 => Self::IpmNoteEntryId,
            0x36D4 => Self::IpmTaskEntryId,
            0x3A2D => Self::IsdnNumber,
            0x6103 => Self::JunkAddRecipientsToSafeSendersList,
            0x6100 => Self::JunkIncludeContacts,
            0x6102 => Self::JunkPermanentlyDelete,
            0x6107 => Self::JunkPhishingEnableLinks,
            0x6101 => Self::JunkThreshold,
            0x3A0B => Self::Keyword,
            0x3A0C => Self::Language,
            0x3008 => Self::LastModificationTime,
            0x3FFB => Self::LastModifierEntryId,
            0x3FFA => Self::LastModifierName,
            0x1081 => Self::LastVerbExecuted,
            0x1082 => Self::LastVerbExecutionTime,
            0x1043 => Self::ListHelp,
            0x1044 => Self::ListSubscribe,
            0x1045 => Self::ListUnsubscribe,
            0x6709 => Self::LocalCommitTime,
            0x670A => Self::LocalCommitTimeMax,
            0x66A1 => Self::LocaleId,
            0x3A27 => Self::Locality,
            0x3A0D => Self::Location,
            0x661B => Self::MailboxOwnerEntryId,
            0x661C => Self::MailboxOwnerName,
            0x3A4E => Self::ManagerName,
            0x0FF8 => Self::MappingSignature,
            0x666D => Self::MaximumSubmitMessageSize,
            0x6671 => Self::MemberId,
            0x6672 => Self::MemberName,
            0x6673 => Self::MemberRights,
            0x0E13 => Self::MessageAttachments,
            0x0058 => Self::MessageCcMe,
            0x001A => Self::MessageClass,
            0x3FFD => Self::MessageCodepage,
            0x0E06 => Self::MessageDeliveryTime,
            0x5909 => Self::MessageEditorFormat,
            0x0E07 => Self::MessageFlags,
            0x3A0F => Self::MessageHandlingSystemCommonName,
            0x3FF1 => Self::MessageLocaleId,
            0x0059 => Self::MessageRecipientMe,
            0x0E12 => Self::MessageRecipients,
            0x0E08 => Self::MessageSize,
            0x0E08 => Self::MessageSizeExtended,
            0x0E17 => Self::MessageStatus,
            0x0047 => Self::MessageSubmissionId,
            0x0057 => Self::MessageToMe,
            0x674A => Self::Mid,
            0x3A44 => Self::MiddleName,
            0x64F0 => Self::MimeSkeleton,
            0x3A1C => Self::MobileTelephoneNumber,
            0x1016 => Self::NativeBody,
            0x0E29 => Self::NextSendAcct,
            0x3A4F => Self::Nickname,
            0x0C05 => Self::NonDeliveryReportDiagCode,
            0x0C04 => Self::NonDeliveryReportReasonCode,
            0x0C20 => Self::NonDeliveryReportStatusCode,
            // export const nReceiptNotificationRequested => 0x0C06,
            0x0E1D => Self::NormalizedSubject,
            0x0FFE => Self::ObjectType,
            0x3A19 => Self::OfficeLocation,
            0x6802 => Self::OfflineAddressBookContainerGuid,
            0x6804 => Self::OfflineAddressBookDistinguishedName,
            0x6803 => Self::OfflineAddressBookMessageClass,
            0x6800 => Self::OfflineAddressBookName,
            0x6801 => Self::OfflineAddressBookSequence,
            0x6805 => Self::OfflineAddressBookTruncatedProperties,
            0x36E2 => Self::OrdinalMost,
            0x3A10 => Self::OrganizationalIdNumber,
            0x004C => Self::OriginalAuthorEntryId,
            0x004D => Self::OriginalAuthorName,
            0x0055 => Self::OriginalDeliveryTime,
            0x0072 => Self::OriginalDisplayBcc,
            0x0073 => Self::OriginalDisplayCc,
            0x0074 => Self::OriginalDisplayTo,
            0x3A12 => Self::OriginalEntryId,
            0x004B => Self::OriginalMessageClass,
            0x1046 => Self::OriginalMessageId,
            0x0066 => Self::OriginalSenderAddressType,
            0x0067 => Self::OriginalSenderEmailAddress,
            0x005B => Self::OriginalSenderEntryId,
            0x005A => Self::OriginalSenderName,
            0x005C => Self::OriginalSenderSearchKey,
            0x002E => Self::OriginalSensitivity,
            0x0068 => Self::OriginalSentRepresentingAddressType,
            0x0069 => Self::OriginalSentRepresentingEmailAddress,
            0x005E => Self::OriginalSentRepresentingEntryId,
            0x005D => Self::OriginalSentRepresentingName,
            0x005F => Self::OriginalSentRepresentingSearchKey,
            0x0049 => Self::OriginalSubject,
            0x004E => Self::OriginalSubmitTime,
            0x0023 => Self::OriginatorDeliveryReportRequested,
            0x0C08 => Self::OriginatorNonDeliveryReportRequested,
            0x7C24 => Self::OscSyncEnabled,
            0x3A5F => Self::OtherAddressCity,
            0x3A60 => Self::OtherAddressCountry,
            0x3A61 => Self::OtherAddressPostalCode,
            0x3A64 => Self::OtherAddressPostOfficeBox,
            0x3A62 => Self::OtherAddressStateOrProvince,
            0x3A63 => Self::OtherAddressStreet,
            0x3A1F => Self::OtherTelephoneNumber,
            0x661D => Self::OutOfOfficeState,
            0x0062 => Self::OwnerAppointmentId,
            0x3A21 => Self::PagerTelephoneNumber,
            0x0E09 => Self::ParentEntryId,
            0x6749 => Self::ParentFolderId,
            0x0025 => Self::ParentKey,
            0x65E1 => Self::ParentSourceKey,
            0x3A50 => Self::PersonalHomePage,
            0x3019 => Self::PolicyTag,
            0x3A15 => Self::PostalAddress,
            0x3A2A => Self::PostalCode,
            0x3A2B => Self::PostOfficeBox,
            0x0048 => Self::ProviderSubmitTime,
            0x65E3 => Self::PredecessorChangeList,
            0x3A23 => Self::PrimaryFaxNumber,
            0x0E28 => Self::PrimarySendAccount,
            0x3A1A => Self::PrimaryTelephoneNumber,
            0x0026 => Self::Priority,
            0x7D01 => Self::Processed,
            0x3A46 => Self::Profession,
            0x666A => Self::ProhibitReceiveQuota,
            0x666E => Self::ProhibitSendQuota,
            0x4083 => Self::PurportedSenderDomain,
            0x3A1D => Self::RadioTelephoneNumber,
            0x0E69 => Self::Read,
            0x4029 => Self::ReadReceiptAddressType,
            0x402A => Self::ReadReceiptEmailAddress,
            0x0046 => Self::ReadReceiptEntryId,
            0x402B => Self::ReadReceiptName,
            0x0029 => Self::ReadReceiptRequested,
            0x0053 => Self::ReadReceiptSearchKey,
            0x5D05 => Self::ReadReceiptSmtpAddress,
            0x002A => Self::ReceiptTime,
            0x0075 => Self::ReceivedByAddressType,
            0x0076 => Self::ReceivedByEmailAddress,
            0x003F => Self::ReceivedByEntryId,
            0x0040 => Self::ReceivedByName,
            0x0051 => Self::ReceivedBySearchKey,
            0x5D07 => Self::ReceivedBySmtpAddress,
            0x0077 => Self::ReceivedRepresentingAddressType,
            0x0078 => Self::ReceivedRepresentingEmailAddress,
            0x0043 => Self::ReceivedRepresentingEntryId,
            0x0044 => Self::ReceivedRepresentingName,
            0x0052 => Self::ReceivedRepresentingSearchKey,
            0x5D08 => Self::ReceivedRepresentingSmtpAddress,
            0x5FF6 => Self::RecipientDisplayName,
            0x5FF7 => Self::RecipientEntryId,
            0x5FFD => Self::RecipientFlags,
            0x5FDF => Self::RecipientOrder,
            0x5FE1 => Self::RecipientProposed,
            0x5FE4 => Self::RecipientProposedEndTime,
            0x5FE3 => Self::RecipientProposedStartTime,
            0x002B => Self::RecipientReassignmentProhibited,
            0x5FFF => Self::RecipientTrackStatus,
            0x5FFB => Self::RecipientTrackStatusTime,
            0x0C15 => Self::RecipientType,
            0x0FF9 => Self::RecordKey,
            0x3A47 => Self::ReferredByName,
            0x36D5 => Self::RemindersOnlineEntryId,
            0x0C21 => Self::RemoteMessageTransferAgent,
            0x370B => Self::RenderingPosition,
            0x004F => Self::ReplyRecipientEntries,
            0x0050 => Self::ReplyRecipientNames,
            0x0C17 => Self::ReplyRequested,
            0x65C2 => Self::ReplyTemplateId,
            0x0030 => Self::ReplyTime,
            0x0080 => Self::ReportDisposition,
            0x0081 => Self::ReportDispositionMode,
            0x0045 => Self::ReportEntryId,
            0x6820 => Self::ReportingMessageTransferAgent,
            0x003A => Self::ReportName,
            0x0054 => Self::ReportSearchKey,
            0x0031 => Self::ReportTag,
            0x1001 => Self::ReportText,
            0x0032 => Self::ReportTime,
            0x3FE7 => Self::ResolveMethod,
            0x0063 => Self::ResponseRequested,
            0x0E0F => Self::Responsibility,
            0x301C => Self::RetentionDate,
            0x301D => Self::RetentionFlags,
            0x301A => Self::RetentionPeriod,
            0x6639 => Self::Rights,
            0x7C06 => Self::RoamingDatatypes,
            0x7C07 => Self::RoamingDictionary,
            0x7C08 => Self::RoamingXmlStream,
            0x3000 => Self::Rowid,
            0x0FF5 => Self::RowType,
            0x1009 => Self::RtfCompressed,
            0x0E1F => Self::RtfInSync,
            0x6650 => Self::RuleActionNumber,
            0x6680 => Self::RuleActions,
            0x6649 => Self::RuleActionType,
            0x6679 => Self::RuleCondition,
            0x6648 => Self::RuleError,
            0x6651 => Self::RuleFolderEntryId,
            0x6674 => Self::RuleId,
            0x6675 => Self::RuleIds,
            0x6683 => Self::RuleLevel,
            0x65ED => Self::RuleMessageLevel,
            0x65EC => Self::RuleMessageName,
            0x65EB => Self::RuleMessageProvider,
            0x65EE => Self::RuleMessageProviderData,
            0x65F3 => Self::RuleMessageSequence,
            0x65E9 => Self::RuleMessageState,
            0x65EA => Self::RuleMessageUserFlags,
            0x6682 => Self::RuleName,
            0x6681 => Self::RuleProvider,
            0x6684 => Self::RuleProviderData,
            0x6676 => Self::RuleSequence,
            0x6677 => Self::RuleState,
            0x6678 => Self::RuleUserFlags,
            0x6802 => Self::RwRulesStream,
            0x686A => Self::ScheduleInfoAppointmentTombstone,
            0x686D => Self::ScheduleInfoAutoAcceptAppointments,
            0x6845 => Self::ScheduleInfoDelegateEntryIds,
            0x6844 => Self::ScheduleInfoDelegateNames,
            0x684A => Self::ScheduleInfoDelegateNamesW,
            0x6842 => Self::ScheduleInfoDelegatorWantsCopy,
            0x684B => Self::ScheduleInfoDelegatorWantsInfo,
            0x686F => Self::ScheduleInfoDisallowOverlappingAppts,
            0x686E => Self::ScheduleInfoDisallowRecurringAppts,
            0x6843 => Self::ScheduleInfoDontMailDelegates,
            0x686C => Self::ScheduleInfoFreeBusy,
            0x6856 => Self::ScheduleInfoFreeBusyAway,
            0x6854 => Self::ScheduleInfoFreeBusyBusy,
            0x6850 => Self::ScheduleInfoFreeBusyMerged,
            0x6852 => Self::ScheduleInfoFreeBusyTentative,
            0x6855 => Self::ScheduleInfoMonthsAway,
            0x6853 => Self::ScheduleInfoMonthsBusy,
            0x684F => Self::ScheduleInfoMonthsMerged,
            0x6851 => Self::ScheduleInfoMonthsTentative,
            0x6841 => Self::ScheduleInfoResourceType,
            0x6622 => Self::SchedulePlusFreeBusyEntryId,
            0x0004 => Self::ScriptData,
            0x6845 => Self::SearchFolderDefinition,
            0x6848 => Self::SearchFolderEfpFlags,
            0x683A => Self::SearchFolderExpiration,
            0x6842 => Self::SearchFolderId,
            0x6834 => Self::SearchFolderLastUsed,
            0x6844 => Self::SearchFolderRecreateInfo,
            0x6846 => Self::SearchFolderStorageType,
            0x6847 => Self::SearchFolderTag,
            0x6841 => Self::SearchFolderTemplateId,
            0x300B => Self::SearchKey,
            0x0E6A => Self::SecurityDescriptorAsXml,
            0x3609 => Self::Selectable,
            0x0C1E => Self::SenderAddressType,
            0x0C1F => Self::SenderEmailAddress,
            0x0C19 => Self::SenderEntryId,
            0x4079 => Self::SenderIdStatus,
            0x0C1A => Self::SenderName,
            0x0C1D => Self::SenderSearchKey,
            0x5D01 => Self::SenderSmtpAddress,
            0x6802 => Self::SenderTelephoneNumber,
            0x3A71 => Self::SendInternetEncoding,
            0x3A40 => Self::SendRichInfo,
            0x0036 => Self::Sensitivity,
            0x6740 => Self::SentMailSvrEID,
            0x0E0A => Self::SentMailEntryId,
            0x0064 => Self::SentRepresentingAddressType,
            0x0065 => Self::SentRepresentingEmailAddress,
            0x0041 => Self::SentRepresentingEntryId,
            0x401A => Self::SentRepresentingFlags,
            0x0042 => Self::SentRepresentingName,
            0x003B => Self::SentRepresentingSearchKey,
            0x5D02 => Self::SentRepresentingSmtpAddress,
            0x6638 => Self::SerializedReplidGuidMap,
            0x39FE => Self::SmtpAddress,
            0x6705 => Self::SortLocaleId,
            0x65E0 => Self::SourceKey,
            0x8CC2 => Self::SpokenName,
            0x3A48 => Self::SpouseName,
            0x0060 => Self::StartDate,
            0x301B => Self::StartDateEtc,
            0x3A28 => Self::StateOrProvince,
            0x0FFB => Self::StoreEntryId,
            0x340E => Self::StoreState,
            0x340D => Self::StoreSupportMask,
            0x3A29 => Self::StreetAddress,
            0x360A => Self::Subfolders,
            0x0037 => Self::Subject,
            0x003D => Self::SubjectPrefix,
            0x0C1B => Self::SupplementaryInfo,
            0x3A11 => Self::Surname,
            0x0E2D => Self::SwappedToDoData,
            0x0E2C => Self::SwappedToDoStore,
            0x3010 => Self::TargetEntryId,
            0x3A4B => Self::TelecommunicationsDeviceForDeafTelephoneNumber,
            0x0001 => Self::TemplateData,
            0x3902 => Self::Templateid,
            0x371B => Self::TextAttachmentCharset,
            0x8C9E => Self::ThumbnailPhoto,
            0x3A17 => Self::Title,
            0x007F => Self::TnefCorrelationKey,
            0x0E2B => Self::ToDoItemFlags,
            0x3A20 => Self::TransmittableDisplayName,
            0x007D => Self::TransportMessageHeaders,
            0x0E79 => Self::TrustSender,
            0x3A22 => Self::UserCertificate,
            0x6619 => Self::UserEntryId,
            0x3A70 => Self::UserX509Certificate,
            0x7001 => Self::ViewDescriptorBinary,
            0x7006 => Self::ViewDescriptorName,
            0x7002 => Self::ViewDescriptorStrings,
            0x7007 => Self::ViewDescriptorVersion,
            0x6805 => Self::VoiceMessageAttachmentOrder,
            0x6801 => Self::VoiceMessageDuration,
            0x6803 => Self::VoiceMessageSenderName,
            0x3A41 => Self::WeddingAnniversary,
            0x6854 => Self::WlinkAddressBookEID,
            0x6891 => Self::WlinkAddressBookStoreEID,
            0x6853 => Self::WlinkCalendarColor,
            0x6890 => Self::WlinkClientID,
            0x684C => Self::WlinkEntryId,
            0x684A => Self::WlinkFlags,
            0x684F => Self::WlinkFolderType,
            0x6850 => Self::WlinkGroupClsid,
            0x6842 => Self::WlinkGroupHeaderID,
            0x6851 => Self::WlinkGroupName,
            0x684B => Self::WlinkOrdinal,
            0x684D => Self::WlinkRecordKey,
            0x6892 => Self::WlinkROGroupType,
            0x6847 => Self::WlinkSaveStamp,
            0x6852 => Self::WlinkSection,
            0x684E => Self::WlinkStoreEntryId,
            0x6849 => Self::WlinkType,
            0x8000..=0xFFFF => Self::Mapped(n),
            n => Self::Unknown(n),
        }
    }
    pub fn to_u16(self) -> u16 {
        match self {
            Self::Access => 0x0FF4,
            Self::AccessControlListData => 0x3FE0,
            Self::AccessLevel => 0x0FF7,
            Self::Account => 0x3A00,
            Self::AdditionalRenEntryIds => 0x36D8,
            Self::AdditionalRenEntryIdsEx => 0x36D9,
            Self::AddressBookAuthorizedSenders => 0x8CD8,
            Self::AddressBookContainerId => 0xFFFD,
            Self::AddressBookDeliveryContentLength => 0x806A,
            Self::AddressBookDisplayNamePrintable => 0x39FF,
            Self::AddressBookDisplayTypeExtended => 0x8C93,
            Self::AddressBookDistributionListExternalMemberCount => 0x8CE3,
            Self::AddressBookDistributionListMemberCount => 0x8CE2,
            Self::AddressBookDistributionListMemberSubmitAccepted => 0x8073,
            Self::AddressBookDistributionListMemberSubmitRejected => 0x8CDA,
            Self::AddressBookDistributionListRejectMessagesFromDLMembers => 0x8CDB,
            Self::AddressBookEntryId => 0x663B,
            Self::AddressBookExtensionAttribute1 => 0x802D,
            Self::AddressBookExtensionAttribute10 => 0x8036,
            Self::AddressBookExtensionAttribute11 => 0x8C57,
            Self::AddressBookExtensionAttribute12 => 0x8C58,
            Self::AddressBookExtensionAttribute13 => 0x8C59,
            Self::AddressBookExtensionAttribute14 => 0x8C60,
            Self::AddressBookExtensionAttribute15 => 0x8C61,
            Self::AddressBookExtensionAttribute2 => 0x802E,
            Self::AddressBookExtensionAttribute3 => 0x802F,
            Self::AddressBookExtensionAttribute4 => 0x8030,
            Self::AddressBookExtensionAttribute5 => 0x8031,
            Self::AddressBookExtensionAttribute6 => 0x8032,
            Self::AddressBookExtensionAttribute7 => 0x8033,
            Self::AddressBookExtensionAttribute8 => 0x8034,
            Self::AddressBookExtensionAttribute9 => 0x8035,
            Self::AddressBookFolderPathname => 0x8004,
            Self::AddressBookHierarchicalChildDepartments => 0x8C9A,
            Self::AddressBookHierarchicalDepartmentMembers => 0x8C97,
            Self::AddressBookHierarchicalIsHierarchicalGroup => 0x8CDD,
            Self::AddressBookHierarchicalParentDepartment => 0x8C99,
            Self::AddressBookHierarchicalRootDepartment => 0x8C98,
            Self::AddressBookHierarchicalShowInDepartments => 0x8C94,
            Self::AddressBookIsMaster => 0xFFFB,
            Self::AddressBookManageDistributionList => 0x6704,
            Self::AddressBookManager => 0x8005,
            Self::AddressBookManagerDistinguishedName => 0x8005,
            Self::AddressBookMember => 0x8009,
            Self::AddressBookMessageId => 0x674F,
            Self::AddressBookModerationEnabled => 0x8CB5,
            Self::AddressBookNetworkAddress => 0x8170,
            Self::AddressBookObjectDistinguishedName => 0x803C,
            Self::AddressBookObjectGuid => 0x8C6D,
            Self::AddressBookOrganizationalUnitRootDistinguishedName => 0x8CA8,
            Self::AddressBookOwner => 0x800C,
            Self::AddressBookOwnerBackLink => 0x8024,
            Self::AddressBookParentEntryId => 0xFFFC,
            Self::AddressBookPhoneticCompanyName => 0x8C91,
            Self::AddressBookPhoneticDepartmentName => 0x8C90,
            Self::AddressBookPhoneticDisplayName => 0x8C92,
            Self::AddressBookPhoneticGivenName => 0x8C8E,
            Self::AddressBookPhoneticSurname => 0x8C8F,
            Self::AddressBookProxyAddresses => 0x800F,
            Self::AddressBookPublicDelegates => 0x8015,
            Self::AddressBookReports => 0x800E,
            Self::AddressBookRoomCapacity => 0x0807,
            Self::AddressBookRoomContainers => 0x8C96,
            Self::AddressBookRoomDescription => 0x0809,
            Self::AddressBookSenderHintTranslations => 0x8CAC,
            Self::AddressBookSeniorityIndex => 0x8CA0,
            Self::AddressBookTargetAddress => 0x8011,
            Self::AddressBookUnauthorizedSenders => 0x8CD9,
            Self::AddressBookX509Certificate => 0x8C6A,
            Self::AddressType => 0x3002,
            Self::AlternateRecipientAllowed => 0x0002,
            Self::Anr => 0x360C,
            Self::ArchiveDate => 0x301F,
            Self::ArchivePeriod => 0x301E,
            Self::ArchiveTag => 0x3018,
            Self::Assistant => 0x3A30,
            Self::AssistantTelephoneNumber => 0x3A2E,
            Self::Associated => 0x67AA,
            Self::AttachAdditionalInformation => 0x370F,
            Self::AttachContentBase => 0x3711,
            Self::AttachContentId => 0x3712,
            Self::AttachContentLocation => 0x3713,
            Self::AttachDataBinary => 0x3701,
            Self::AttachDataObject => 0x3701,
            Self::AttachEncoding => 0x3702,
            Self::AttachExtension => 0x3703,
            Self::AttachFilename => 0x3704,
            Self::AttachFlags => 0x3714,
            Self::AttachLongFilename => 0x3707,
            Self::AttachLongPathname => 0x370D,
            Self::AttachmentContactPhoto => 0x7FFF,
            Self::AttachmentFlags => 0x7FFD,
            Self::AttachmentHidden => 0x7FFE,
            Self::AttachmentLinkId => 0x7FFA,
            Self::AttachMethod => 0x3705,
            Self::AttachMimeTag => 0x370E,
            Self::AttachNumber => 0x0E21,
            Self::AttachPathname => 0x3708,
            Self::AttachPayloadClass => 0x371A,
            Self::AttachPayloadProviderGuidString => 0x3719,
            Self::AttachRendering => 0x3709,
            Self::AttachSize => 0x0E20,
            Self::AttachTag => 0x370A,
            Self::AttachTransportName => 0x370C,
            Self::AttributeHidden => 0x10F4,
            Self::AttributeReadOnly => 0x10F6,
            Self::AutoForwardComment => 0x0004,
            Self::AutoForwarded => 0x0005,
            Self::AutoResponseSuppress => 0x3FDF,
            Self::Birthday => 0x3A42,
            Self::BlockStatus => 0x1096,
            Self::Body => 0x1000,
            Self::BodyContentId => 0x1015,
            Self::BodyContentLocation => 0x1014,
            Self::BodyHtml => 0x1013,
            Self::Business2TelephoneNumber => 0x3A1B,
            Self::Business2TelephoneNumbers => 0x3A1B,
            Self::BusinessFaxNumber => 0x3A24,
            Self::BusinessHomePage => 0x3A51,
            Self::BusinessTelephoneNumber => 0x3A08,
            Self::CallbackTelephoneNumber => 0x3A02,
            Self::CallId => 0x6806,
            Self::CarTelephoneNumber => 0x3A1E,
            Self::CdoRecurrenceid => 0x10C5,
            Self::ChangeKey => 0x65E2,
            Self::ChangeNumber => 0x67A4,
            Self::ChildrensNames => 0x3A58,
            Self::ClientActions => 0x6645,
            Self::ClientSubmitTime => 0x0039,
            Self::CodePageId => 0x66C3,
            Self::Comment => 0x3004,
            Self::CompanyMainTelephoneNumber => 0x3A57,
            Self::CompanyName => 0x3A16,
            Self::ComputerNetworkName => 0x3A49,
            Self::ConflictEntryId => 0x3FF0,
            Self::ContainerClass => 0x3613,
            Self::ContainerContents => 0x360F,
            Self::ContainerFlags => 0x3600,
            Self::ContainerHierarchy => 0x360E,
            Self::ContentCount => 0x3602,
            Self::ContentFilterSpamConfidenceLevel => 0x4076,
            Self::ContentUnreadCount => 0x3603,
            Self::ConversationId => 0x3013,
            Self::ConversationIndex => 0x0071,
            Self::ConversationIndexTracking => 0x3016,
            Self::ConversationTopic => 0x0070,
            Self::Country => 0x3A26,
            Self::CreationTime => 0x3007,
            Self::CreatorEntryId => 0x3FF9,
            Self::CreatorName => 0x3FF8,
            Self::CustomerId => 0x3A4A,
            Self::DamBackPatched => 0x6647,
            Self::DamOriginalEntryId => 0x6646,
            Self::DefaultPostMessageClass => 0x36E5,
            Self::DeferredActionMessageOriginalEntryId => 0x6741,
            Self::DeferredDeliveryTime => 0x000F,
            Self::DeferredSendNumber => 0x3FEB,
            Self::DeferredSendTime => 0x3FEF,
            Self::DeferredSendUnits => 0x3FEC,
            Self::DelegatedByRule => 0x3FE3,
            Self::DelegateFlags => 0x686B,
            Self::DeleteAfterSubmit => 0x0E01,
            Self::DeletedCountTotal => 0x670B,
            Self::DeletedOn => 0x668F,
            Self::DeliverTime => 0x0010,
            Self::DepartmentName => 0x3A18,
            Self::Depth => 0x3005,
            Self::DisplayBcc => 0x0E02,
            Self::DisplayCc => 0x0E03,
            Self::DisplayName => 0x3001,
            Self::DisplayNamePrefix => 0x3A45,
            Self::DisplayTo => 0x0E04,
            Self::DisplayType => 0x3900,
            Self::DisplayTypeEx => 0x3905,
            Self::EmailAddress => 0x3003,
            Self::EndDate => 0x0061,
            Self::EntryId => 0x0FFF,
            Self::ExceptionEndTime => 0x7FFC,
            Self::ExceptionReplaceTime => 0x7FF9,
            Self::ExceptionStartTime => 0x7FFB,
            Self::ExchangeNTSecurityDescriptor => 0x0E84,
            Self::ExpiryNumber => 0x3FED,
            Self::ExpiryTime => 0x0015,
            Self::ExpiryUnits => 0x3FEE,
            Self::ExtendedFolderFlags => 0x36DA,
            Self::ExtendedRuleMessageActions => 0x0E99,
            Self::ExtendedRuleMessageCondition => 0x0E9A,
            Self::ExtendedRuleSizeLimit => 0x0E9B,
            Self::FaxNumberOfPages => 0x6804,
            Self::FlagCompleteTime => 0x1091,
            Self::FlagStatus => 0x1090,
            Self::FlatUrlName => 0x670E,
            Self::FolderAssociatedContents => 0x3610,
            Self::FolderId => 0x6748,
            Self::FolderFlags => 0x66A8,
            Self::FolderType => 0x3601,
            Self::FollowupIcon => 0x1095,
            Self::FreeBusyCountMonths => 0x6869,
            Self::FreeBusyEntryIds => 0x36E4,
            Self::FreeBusyMessageEmailAddress => 0x6849,
            Self::FreeBusyPublishEnd => 0x6848,
            Self::FreeBusyPublishStart => 0x6847,
            Self::FreeBusyRangeTimestamp => 0x6868,
            Self::FtpSite => 0x3A4C,
            Self::GatewayNeedsToRefresh => 0x6846,
            Self::Gender => 0x3A4D,
            Self::Generation => 0x3A05,
            Self::GivenName => 0x3A06,
            Self::GovernmentIdNumber => 0x3A07,
            Self::HasAttachments => 0x0E1B,
            Self::HasDeferredActionMessages => 0x3FEA,
            Self::HasNamedProperties => 0x664A,
            Self::HasRules => 0x663A,
            Self::HierarchyChangeNumber => 0x663E,
            Self::HierRev => 0x4082,
            Self::Hobbies => 0x3A43,
            Self::Home2TelephoneNumber => 0x3A2F,
            Self::Home2TelephoneNumbers => 0x3A2F,
            Self::HomeAddressCity => 0x3A59,
            Self::HomeAddressCountry => 0x3A5A,
            Self::HomeAddressPostalCode => 0x3A5B,
            Self::HomeAddressPostOfficeBox => 0x3A5E,
            Self::HomeAddressStateOrProvince => 0x3A5C,
            Self::HomeAddressStreet => 0x3A5D,
            Self::HomeFaxNumber => 0x3A25,
            Self::HomeTelephoneNumber => 0x3A09,
            Self::Html => 0x1013,
            Self::ICalendarEndTime => 0x10C4,
            Self::ICalendarReminderNextTime => 0x10CA,
            Self::ICalendarStartTime => 0x10C3,
            Self::IconIndex => 0x1080,
            Self::Importance => 0x0017,
            Self::InConflict => 0x666C,
            Self::InitialDetailsPane => 0x3F08,
            Self::Initials => 0x3A0A,
            Self::InReplyToId => 0x1042,
            Self::InstanceKey => 0x0FF6,
            Self::InstanceNum => 0x674E,
            Self::InstID => 0x674D,
            Self::InternetCodepage => 0x3FDE,
            Self::InternetMailOverrideFormat => 0x5902,
            Self::InternetMessageId => 0x1035,
            Self::InternetReferences => 0x1039,
            Self::IpmAppointmentEntryId => 0x36D0,
            Self::IpmContactEntryId => 0x36D1,
            Self::IpmDraftsEntryId => 0x36D7,
            Self::IpmJournalEntryId => 0x36D2,
            Self::IpmNoteEntryId => 0x36D3,
            Self::IpmTaskEntryId => 0x36D4,
            Self::IsdnNumber => 0x3A2D,
            Self::JunkAddRecipientsToSafeSendersList => 0x6103,
            Self::JunkIncludeContacts => 0x6100,
            Self::JunkPermanentlyDelete => 0x6102,
            Self::JunkPhishingEnableLinks => 0x6107,
            Self::JunkThreshold => 0x6101,
            Self::Keyword => 0x3A0B,
            Self::Language => 0x3A0C,
            Self::LastModificationTime => 0x3008,
            Self::LastModifierEntryId => 0x3FFB,
            Self::LastModifierName => 0x3FFA,
            Self::LastVerbExecuted => 0x1081,
            Self::LastVerbExecutionTime => 0x1082,
            Self::ListHelp => 0x1043,
            Self::ListSubscribe => 0x1044,
            Self::ListUnsubscribe => 0x1045,
            Self::LocalCommitTime => 0x6709,
            Self::LocalCommitTimeMax => 0x670A,
            Self::LocaleId => 0x66A1,
            Self::Locality => 0x3A27,
            Self::Location => 0x3A0D,
            Self::MailboxOwnerEntryId => 0x661B,
            Self::MailboxOwnerName => 0x661C,
            Self::ManagerName => 0x3A4E,
            Self::MappingSignature => 0x0FF8,
            Self::MaximumSubmitMessageSize => 0x666D,
            Self::MemberId => 0x6671,
            Self::MemberName => 0x6672,
            Self::MemberRights => 0x6673,
            Self::MessageAttachments => 0x0E13,
            Self::MessageCcMe => 0x0058,
            Self::MessageClass => 0x001A,
            Self::MessageCodepage => 0x3FFD,
            Self::MessageDeliveryTime => 0x0E06,
            Self::MessageEditorFormat => 0x5909,
            Self::MessageFlags => 0x0E07,
            Self::MessageHandlingSystemCommonName => 0x3A0F,
            Self::MessageLocaleId => 0x3FF1,
            Self::MessageRecipientMe => 0x0059,
            Self::MessageRecipients => 0x0E12,
            Self::MessageSize => 0x0E08,
            Self::MessageSizeExtended => 0x0E08,
            Self::MessageStatus => 0x0E17,
            Self::MessageSubmissionId => 0x0047,
            Self::MessageToMe => 0x0057,
            Self::Mid => 0x674A,
            Self::MiddleName => 0x3A44,
            Self::MimeSkeleton => 0x64F0,
            Self::MobileTelephoneNumber => 0x3A1C,
            Self::NativeBody => 0x1016,
            Self::NextSendAcct => 0x0E29,
            Self::Nickname => 0x3A4F,
            Self::NonDeliveryReportDiagCode => 0x0C05,
            Self::NonDeliveryReportReasonCode => 0x0C04,
            Self::NonDeliveryReportStatusCode => 0x0C20,
            // export const nReceiptNotificationRequested => 0x0C06,
            Self::NormalizedSubject => 0x0E1D,
            Self::ObjectType => 0x0FFE,
            Self::OfficeLocation => 0x3A19,
            Self::OfflineAddressBookContainerGuid => 0x6802,
            Self::OfflineAddressBookDistinguishedName => 0x6804,
            Self::OfflineAddressBookMessageClass => 0x6803,
            Self::OfflineAddressBookName => 0x6800,
            Self::OfflineAddressBookSequence => 0x6801,
            Self::OfflineAddressBookTruncatedProperties => 0x6805,
            Self::OrdinalMost => 0x36E2,
            Self::OrganizationalIdNumber => 0x3A10,
            Self::OriginalAuthorEntryId => 0x004C,
            Self::OriginalAuthorName => 0x004D,
            Self::OriginalDeliveryTime => 0x0055,
            Self::OriginalDisplayBcc => 0x0072,
            Self::OriginalDisplayCc => 0x0073,
            Self::OriginalDisplayTo => 0x0074,
            Self::OriginalEntryId => 0x3A12,
            Self::OriginalMessageClass => 0x004B,
            Self::OriginalMessageId => 0x1046,
            Self::OriginalSenderAddressType => 0x0066,
            Self::OriginalSenderEmailAddress => 0x0067,
            Self::OriginalSenderEntryId => 0x005B,
            Self::OriginalSenderName => 0x005A,
            Self::OriginalSenderSearchKey => 0x005C,
            Self::OriginalSensitivity => 0x002E,
            Self::OriginalSentRepresentingAddressType => 0x0068,
            Self::OriginalSentRepresentingEmailAddress => 0x0069,
            Self::OriginalSentRepresentingEntryId => 0x005E,
            Self::OriginalSentRepresentingName => 0x005D,
            Self::OriginalSentRepresentingSearchKey => 0x005F,
            Self::OriginalSubject => 0x0049,
            Self::OriginalSubmitTime => 0x004E,
            Self::OriginatorDeliveryReportRequested => 0x0023,
            Self::OriginatorNonDeliveryReportRequested => 0x0C08,
            Self::OscSyncEnabled => 0x7C24,
            Self::OtherAddressCity => 0x3A5F,
            Self::OtherAddressCountry => 0x3A60,
            Self::OtherAddressPostalCode => 0x3A61,
            Self::OtherAddressPostOfficeBox => 0x3A64,
            Self::OtherAddressStateOrProvince => 0x3A62,
            Self::OtherAddressStreet => 0x3A63,
            Self::OtherTelephoneNumber => 0x3A1F,
            Self::OutOfOfficeState => 0x661D,
            Self::OwnerAppointmentId => 0x0062,
            Self::PagerTelephoneNumber => 0x3A21,
            Self::ParentEntryId => 0x0E09,
            Self::ParentFolderId => 0x6749,
            Self::ParentKey => 0x0025,
            Self::ParentSourceKey => 0x65E1,
            Self::PersonalHomePage => 0x3A50,
            Self::PolicyTag => 0x3019,
            Self::PostalAddress => 0x3A15,
            Self::PostalCode => 0x3A2A,
            Self::PostOfficeBox => 0x3A2B,
            Self::ProviderSubmitTime => 0x0048,
            Self::PredecessorChangeList => 0x65E3,
            Self::PrimaryFaxNumber => 0x3A23,
            Self::PrimarySendAccount => 0x0E28,
            Self::PrimaryTelephoneNumber => 0x3A1A,
            Self::Priority => 0x0026,
            Self::Processed => 0x7D01,
            Self::Profession => 0x3A46,
            Self::ProhibitReceiveQuota => 0x666A,
            Self::ProhibitSendQuota => 0x666E,
            Self::PurportedSenderDomain => 0x4083,
            Self::RadioTelephoneNumber => 0x3A1D,
            Self::Read => 0x0E69,
            Self::ReadReceiptAddressType => 0x4029,
            Self::ReadReceiptEmailAddress => 0x402A,
            Self::ReadReceiptEntryId => 0x0046,
            Self::ReadReceiptName => 0x402B,
            Self::ReadReceiptRequested => 0x0029,
            Self::ReadReceiptSearchKey => 0x0053,
            Self::ReadReceiptSmtpAddress => 0x5D05,
            Self::ReceiptTime => 0x002A,
            Self::ReceivedByAddressType => 0x0075,
            Self::ReceivedByEmailAddress => 0x0076,
            Self::ReceivedByEntryId => 0x003F,
            Self::ReceivedByName => 0x0040,
            Self::ReceivedBySearchKey => 0x0051,
            Self::ReceivedBySmtpAddress => 0x5D07,
            Self::ReceivedRepresentingAddressType => 0x0077,
            Self::ReceivedRepresentingEmailAddress => 0x0078,
            Self::ReceivedRepresentingEntryId => 0x0043,
            Self::ReceivedRepresentingName => 0x0044,
            Self::ReceivedRepresentingSearchKey => 0x0052,
            Self::ReceivedRepresentingSmtpAddress => 0x5D08,
            Self::RecipientDisplayName => 0x5FF6,
            Self::RecipientEntryId => 0x5FF7,
            Self::RecipientFlags => 0x5FFD,
            Self::RecipientOrder => 0x5FDF,
            Self::RecipientProposed => 0x5FE1,
            Self::RecipientProposedEndTime => 0x5FE4,
            Self::RecipientProposedStartTime => 0x5FE3,
            Self::RecipientReassignmentProhibited => 0x002B,
            Self::RecipientTrackStatus => 0x5FFF,
            Self::RecipientTrackStatusTime => 0x5FFB,
            Self::RecipientType => 0x0C15,
            Self::RecordKey => 0x0FF9,
            Self::ReferredByName => 0x3A47,
            Self::RemindersOnlineEntryId => 0x36D5,
            Self::RemoteMessageTransferAgent => 0x0C21,
            Self::RenderingPosition => 0x370B,
            Self::ReplyRecipientEntries => 0x004F,
            Self::ReplyRecipientNames => 0x0050,
            Self::ReplyRequested => 0x0C17,
            Self::ReplyTemplateId => 0x65C2,
            Self::ReplyTime => 0x0030,
            Self::ReportDisposition => 0x0080,
            Self::ReportDispositionMode => 0x0081,
            Self::ReportEntryId => 0x0045,
            Self::ReportingMessageTransferAgent => 0x6820,
            Self::ReportName => 0x003A,
            Self::ReportSearchKey => 0x0054,
            Self::ReportTag => 0x0031,
            Self::ReportText => 0x1001,
            Self::ReportTime => 0x0032,
            Self::ResolveMethod => 0x3FE7,
            Self::ResponseRequested => 0x0063,
            Self::Responsibility => 0x0E0F,
            Self::RetentionDate => 0x301C,
            Self::RetentionFlags => 0x301D,
            Self::RetentionPeriod => 0x301A,
            Self::Rights => 0x6639,
            Self::RoamingDatatypes => 0x7C06,
            Self::RoamingDictionary => 0x7C07,
            Self::RoamingXmlStream => 0x7C08,
            Self::Rowid => 0x3000,
            Self::RowType => 0x0FF5,
            Self::RtfCompressed => 0x1009,
            Self::RtfInSync => 0x0E1F,
            Self::RuleActionNumber => 0x6650,
            Self::RuleActions => 0x6680,
            Self::RuleActionType => 0x6649,
            Self::RuleCondition => 0x6679,
            Self::RuleError => 0x6648,
            Self::RuleFolderEntryId => 0x6651,
            Self::RuleId => 0x6674,
            Self::RuleIds => 0x6675,
            Self::RuleLevel => 0x6683,
            Self::RuleMessageLevel => 0x65ED,
            Self::RuleMessageName => 0x65EC,
            Self::RuleMessageProvider => 0x65EB,
            Self::RuleMessageProviderData => 0x65EE,
            Self::RuleMessageSequence => 0x65F3,
            Self::RuleMessageState => 0x65E9,
            Self::RuleMessageUserFlags => 0x65EA,
            Self::RuleName => 0x6682,
            Self::RuleProvider => 0x6681,
            Self::RuleProviderData => 0x6684,
            Self::RuleSequence => 0x6676,
            Self::RuleState => 0x6677,
            Self::RuleUserFlags => 0x6678,
            Self::RwRulesStream => 0x6802,
            Self::ScheduleInfoAppointmentTombstone => 0x686A,
            Self::ScheduleInfoAutoAcceptAppointments => 0x686D,
            Self::ScheduleInfoDelegateEntryIds => 0x6845,
            Self::ScheduleInfoDelegateNames => 0x6844,
            Self::ScheduleInfoDelegateNamesW => 0x684A,
            Self::ScheduleInfoDelegatorWantsCopy => 0x6842,
            Self::ScheduleInfoDelegatorWantsInfo => 0x684B,
            Self::ScheduleInfoDisallowOverlappingAppts => 0x686F,
            Self::ScheduleInfoDisallowRecurringAppts => 0x686E,
            Self::ScheduleInfoDontMailDelegates => 0x6843,
            Self::ScheduleInfoFreeBusy => 0x686C,
            Self::ScheduleInfoFreeBusyAway => 0x6856,
            Self::ScheduleInfoFreeBusyBusy => 0x6854,
            Self::ScheduleInfoFreeBusyMerged => 0x6850,
            Self::ScheduleInfoFreeBusyTentative => 0x6852,
            Self::ScheduleInfoMonthsAway => 0x6855,
            Self::ScheduleInfoMonthsBusy => 0x6853,
            Self::ScheduleInfoMonthsMerged => 0x684F,
            Self::ScheduleInfoMonthsTentative => 0x6851,
            Self::ScheduleInfoResourceType => 0x6841,
            Self::SchedulePlusFreeBusyEntryId => 0x6622,
            Self::ScriptData => 0x0004,
            Self::SearchFolderDefinition => 0x6845,
            Self::SearchFolderEfpFlags => 0x6848,
            Self::SearchFolderExpiration => 0x683A,
            Self::SearchFolderId => 0x6842,
            Self::SearchFolderLastUsed => 0x6834,
            Self::SearchFolderRecreateInfo => 0x6844,
            Self::SearchFolderStorageType => 0x6846,
            Self::SearchFolderTag => 0x6847,
            Self::SearchFolderTemplateId => 0x6841,
            Self::SearchKey => 0x300B,
            Self::SecurityDescriptorAsXml => 0x0E6A,
            Self::Selectable => 0x3609,
            Self::SenderAddressType => 0x0C1E,
            Self::SenderEmailAddress => 0x0C1F,
            Self::SenderEntryId => 0x0C19,
            Self::SenderIdStatus => 0x4079,
            Self::SenderName => 0x0C1A,
            Self::SenderSearchKey => 0x0C1D,
            Self::SenderSmtpAddress => 0x5D01,
            Self::SenderTelephoneNumber => 0x6802,
            Self::SendInternetEncoding => 0x3A71,
            Self::SendRichInfo => 0x3A40,
            Self::Sensitivity => 0x0036,
            Self::SentMailSvrEID => 0x6740,
            Self::SentMailEntryId => 0x0E0A,
            Self::SentRepresentingAddressType => 0x0064,
            Self::SentRepresentingEmailAddress => 0x0065,
            Self::SentRepresentingEntryId => 0x0041,
            Self::SentRepresentingFlags => 0x401A,
            Self::SentRepresentingName => 0x0042,
            Self::SentRepresentingSearchKey => 0x003B,
            Self::SentRepresentingSmtpAddress => 0x5D02,
            Self::SerializedReplidGuidMap => 0x6638,
            Self::SmtpAddress => 0x39FE,
            Self::SortLocaleId => 0x6705,
            Self::SourceKey => 0x65E0,
            Self::SpokenName => 0x8CC2,
            Self::SpouseName => 0x3A48,
            Self::StartDate => 0x0060,
            Self::StartDateEtc => 0x301B,
            Self::StateOrProvince => 0x3A28,
            Self::StoreEntryId => 0x0FFB,
            Self::StoreState => 0x340E,
            Self::StoreSupportMask => 0x340D,
            Self::StreetAddress => 0x3A29,
            Self::Subfolders => 0x360A,
            Self::Subject => 0x0037,
            Self::SubjectPrefix => 0x003D,
            Self::SupplementaryInfo => 0x0C1B,
            Self::Surname => 0x3A11,
            Self::SwappedToDoData => 0x0E2D,
            Self::SwappedToDoStore => 0x0E2C,
            Self::TargetEntryId => 0x3010,
            Self::TelecommunicationsDeviceForDeafTelephoneNumber => 0x3A4B,
            Self::TemplateData => 0x0001,
            Self::Templateid => 0x3902,
            Self::TextAttachmentCharset => 0x371B,
            Self::ThumbnailPhoto => 0x8C9E,
            Self::Title => 0x3A17,
            Self::TnefCorrelationKey => 0x007F,
            Self::ToDoItemFlags => 0x0E2B,
            Self::TransmittableDisplayName => 0x3A20,
            Self::TransportMessageHeaders => 0x007D,
            Self::TrustSender => 0x0E79,
            Self::UserCertificate => 0x3A22,
            Self::UserEntryId => 0x6619,
            Self::UserX509Certificate => 0x3A70,
            Self::ViewDescriptorBinary => 0x7001,
            Self::ViewDescriptorName => 0x7006,
            Self::ViewDescriptorStrings => 0x7002,
            Self::ViewDescriptorVersion => 0x7007,
            Self::VoiceMessageAttachmentOrder => 0x6805,
            Self::VoiceMessageDuration => 0x6801,
            Self::VoiceMessageSenderName => 0x6803,
            Self::WeddingAnniversary => 0x3A41,
            Self::WlinkAddressBookEID => 0x6854,
            Self::WlinkAddressBookStoreEID => 0x6891,
            Self::WlinkCalendarColor => 0x6853,
            Self::WlinkClientID => 0x6890,
            Self::WlinkEntryId => 0x684C,
            Self::WlinkFlags => 0x684A,
            Self::WlinkFolderType => 0x684F,
            Self::WlinkGroupClsid => 0x6850,
            Self::WlinkGroupHeaderID => 0x6842,
            Self::WlinkGroupName => 0x6851,
            Self::WlinkOrdinal => 0x684B,
            Self::WlinkRecordKey => 0x684D,
            Self::WlinkROGroupType => 0x6892,
            Self::WlinkSaveStamp => 0x6847,
            Self::WlinkSection => 0x6852,
            Self::WlinkStoreEntryId => 0x684E,
            Self::WlinkType => 0x6849,
            Self::Mapped(n) => n,
            Self::Unknown(n) => n,
        }
    }
}
